# -*- coding: utf-8 -*-
"""Access.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3OsCxJjFzIqO7Fg3pUl36Odf3A5eqnC
"""

import pyodbc
import pandas as pd
obSQL = pyodbc.connect(r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=Cursos.accdb')
pd1 = pd.read_sql_query("SELECT * FROM Consulta", obSQL)
print(pd1)