# -*- coding: utf-8 -*-
"""arboldecision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7SzqSpoelOYhSH5ywqe4lR7zdSd_BDS
"""

# Commented out IPython magic to ensure Python compatibility.
#librerias
import pandas as pd
import numpy as np
from sklearn import datasets
FEATURE_NAMES = ['Sepal Lenght', 'Sepal Width', 'Petal Lenght', 'Petal Width']

#cargar datasets
iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns = FEATURE_NAMES)
y = iris.target

#declarar decisor y ajuste del modelo
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X,y)

from sklearn.tree import export_graphviz
export_graphviz(model, 'tree.dot', feature_names = FEATURE_NAMES)

#generar imagen
! dot -Tpng tree.dot -o tree.png

import matplotlib.pyplot as plt
import cv2
# %matplotlib inline
img = cv2.imread('tree.png')
plt.figure(figsize = (20,20))
plt.imshow(img)

