# -*- coding: utf-8 -*-
"""LinearRegresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g38UNCVcIFSSSvzYqrwjGdHlP55G-3y9
"""

#Regresión lineal simple
#1. Crear un diagrama de dispersión de la variable “temp2” y
#las variables independientes
#“edad”, “dilataci” y “expulsiv”.
#Paso1.- cargar la base de datos "Epidural.xlsx"
import pandas as pd
datos = pd.read_excel("Epidural.xlsx")
#Crear diagrama de dispersión
#Paso 2.- Cargar las librerías necesarias
import matplotlib.pyplot as plt
import numpy as np
#Paso 3.- A continuación seleccionamos las variables para crear
# el diagrama de dispersión
# Tenemos en cuenta el nombre del campo (coincidir)
print (datos)
# Calcular la pendiente e intersección de la línea de regresión
# Utilizar  función polyfit(), de numpy
x = datos['edad']
y = datos['TEMP2']
m, b = np.polyfit(x, y, 1)
#Paso 4.- Crear el gráfico
plt.scatter(x, y, color='b')
plt.plot(x, m*x + b, color='r', label='Línea de regresión')
plt.xlabel('edad')
plt.ylabel('Temperatura después del parto')
plt.title('Diagrama de Dispersión I')
plt.legend()
plt.show()