# -*- coding: utf-8 -*-
"""practicas_indice_online.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRtitsWRUdeCdYGZxcHikXggsLBdku8B
"""

# creación por JTD (marzo.2024)
# actividad (curso: DATA SCIENTIST. práctica (optativa): Dataframes Pandas))
# tabla de ciudades (población y áreas); por repositorio (librería) Pandas
# creación de índices para población
# imprimir resultado
import pandas as pd
dict = {
       "Ciudad": ["Madrid","Barcelona","Sevilla"],
    "Población": [3.3,1.6,0.7],
         "Área": [604.3,101.4,140.8]}
pobla=pd.DataFrame(dict)
pobla.index=["MA","BA","SE"]
print (pobla)



# Commented out IPython magic to ensure Python compatibility.
#from IPython.display import Image
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
#import warnings warnings.simplefilter("ignore")
# %matplotlib inline

# figuritas grandes
plt.rcParams['figure.figsize'] = [10, 10]

#from sklearn.datasets import load_boston
#from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

X = pd.DataFrame(housing.data, columns=housing.feature_names)
y = housing.target
X.head()

# @title AveBedrms

from matplotlib import pyplot as plt
X['AveBedrms'].plot(kind='line', figsize=(8, 4), title='AveBedrms')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['MedInc']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_20.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('MedInc')
